import crypto from 'crypto';
import { DatabaseSchema, Role, RoleId, Permission } from './types.js';
import { hashPassword } from '../utils/password.js';

export { hashPassword };

export function generateSeedData(): DatabaseSchema {
  const now = new Date().toISOString();

  // 1. ROLES
  const roles: Role[] = [
    {
      id: 'SUPER_ADMIN_JMF',
      name: 'Super Admin JMF',
      description: 'Administrateur système global JMF Mobility Services avec accès multi-entreprises.',
      is_system: true,
    },
    {
      id: 'COMPANY_ADMIN',
      name: 'Administrateur Entreprise',
      description: 'Direction ou gestionnaire principal de la société cliente.',
      is_system: true,
    },
    {
      id: 'FLEET_MANAGER',
      name: 'Gestionnaire de Flotte',
      description: 'Responsable opérationnel du parc automobile, des affectations et des entretiens.',
      is_system: true,
    },
    {
      id: 'MAINTENANCE_MANAGER',
      name: 'Responsable Maintenance',
      description: 'Supervise les ateliers, les ordres de travail et les pannes.',
      is_system: true,
    },
    {
      id: 'FINANCE_MANAGER',
      name: 'Responsable Financier',
      description: 'Suivi des coûts d’exploitation, factures et calcul du TCO.',
      is_system: true,
    },
    {
      id: 'DRIVER',
      name: 'Conducteur',
      description: 'Accès mobile ou espace personnel : déclarations pleins, pannes, trajets.',
      is_system: true,
    },
    {
      id: 'CLIENT',
      name: 'Client / Donneur d’ordre',
      description: 'Accès espace client simplifié : consultation des véhicules, suivi convoyage et factures.',
      is_system: true,
    },
    {
      id: 'AUDITOR',
      name: 'Auditeur / Observateur',
      description: 'Accès en lecture seule pour contrôle de conformité et audit.',
      is_system: true,
    },
  ];

  // 2. PERMISSIONS
  const permissions: Permission[] = [
    { id: 'companies.view', name: 'Voir les entreprises', module: 'Sociétés' },
    { id: 'companies.manage', name: 'Gérer les entreprises', module: 'Sociétés' },
    { id: 'vehicles.view', name: 'Consulter la flotte', module: 'Véhicules' },
    { id: 'vehicles.create', name: 'Créer un véhicule', module: 'Véhicules' },
    { id: 'vehicles.edit', name: 'Modifier un véhicule', module: 'Véhicules' },
    { id: 'vehicles.delete', name: 'Supprimer / Réformer un véhicule', module: 'Véhicules' },
    { id: 'drivers.view', name: 'Consulter les conducteurs', module: 'Conducteurs' },
    { id: 'drivers.manage', name: 'Gérer les conducteurs', module: 'Conducteurs' },
    { id: 'assignments.manage', name: 'Gérer les affectations', module: 'Affectations' },
    { id: 'maintenance.view', name: 'Consulter la maintenance', module: 'Maintenance' },
    { id: 'maintenance.manage', name: 'Gérer les ordres de travail et pannes', module: 'Maintenance' },
    { id: 'fuel.view', name: 'Consulter le carburant', module: 'Carburant' },
    { id: 'fuel.create', name: 'Enregistrer un plein', module: 'Carburant' },
    { id: 'documents.view', name: 'Consulter les documents', module: 'Documents' },
    { id: 'documents.manage', name: 'Gérer les documents et assurances', module: 'Documents' },
    { id: 'finances.view', name: 'Consulter les coûts et TCO', module: 'Finances' },
    { id: 'invoices.view', name: 'Consulter les factures', module: 'Facturation' },
    { id: 'invoices.manage', name: 'Créer et administrer les factures', module: 'Facturation' },
    { id: 'convoy.view', name: 'Consulter les demandes de convoyage', module: 'Convoyage' },
    { id: 'convoy.create', name: 'Soumettre une demande de convoyage', module: 'Convoyage' },
    { id: 'convoy.manage', name: 'Gérer et affecter les missions de convoyage', module: 'Convoyage' },
    { id: 'telematics.view', name: 'Consulter la télématique et géolocalisation', module: 'Télématique' },
    { id: 'reports.view', name: 'Générer et exporter les rapports', module: 'Rapports' },
    { id: 'settings.manage', name: 'Gérer les paramètres et utilisateurs', module: 'Paramètres' },
  ];

  // Role permissions mappings
  const role_permissions: { role_id: RoleId; permission_id: string }[] = [
    // Super admin has all permissions
    ...permissions.map(p => ({ role_id: 'SUPER_ADMIN_JMF' as RoleId, permission_id: p.id })),
    // Company admin has company permissions
    ...permissions
      .filter(p => !['companies.manage', 'settings.manage'].includes(p.id))
      .map(p => ({ role_id: 'COMPANY_ADMIN' as RoleId, permission_id: p.id })),
    { role_id: 'COMPANY_ADMIN', permission_id: 'settings.manage' },
    // Client has restricted client permissions
    { role_id: 'CLIENT', permission_id: 'vehicles.view' },
    { role_id: 'CLIENT', permission_id: 'invoices.view' },
    { role_id: 'CLIENT', permission_id: 'convoy.view' },
    { role_id: 'CLIENT', permission_id: 'convoy.create' },
    { role_id: 'CLIENT', permission_id: 'documents.view' },
    // Driver permissions
    { role_id: 'DRIVER', permission_id: 'vehicles.view' },
    { role_id: 'DRIVER', permission_id: 'fuel.create' },
    { role_id: 'DRIVER', permission_id: 'documents.view' },
    { role_id: 'DRIVER', permission_id: 'convoy.view' },
    // Finance Manager
    { role_id: 'FINANCE_MANAGER', permission_id: 'finances.view' },
    { role_id: 'FINANCE_MANAGER', permission_id: 'invoices.view' },
    { role_id: 'FINANCE_MANAGER', permission_id: 'invoices.manage' },
    { role_id: 'FINANCE_MANAGER', permission_id: 'reports.view' },
    { role_id: 'FINANCE_MANAGER', permission_id: 'vehicles.view' },
  ];

  // 3. COMPANIES (Tenants)
  const company1Id = 'comp_jmf_client_001'; // Société Cliente SARL (matches mockup)
  const company2Id = 'comp_bollore_002';    // Bolloré Transport & Logistics (Tenant 2 for isolation testing)

  const companies = [
    {
      id: company1Id,
      name: 'Société Cliente SARL',
      legal_name: 'Société Cliente SARL Bénin',
      registration_number: 'RB/COT/21 B 14234',
      tax_number: 'IFU 0202110293849',
      email: 'contact@societe-cliente.com',
      phone: '+229 21 31 45 00',
      address: 'Boulevard de la Marina, Lot 45',
      city: 'Cotonou',
      country: 'Bénin',
      currency: 'FCFA',
      timezone: 'Africa/Porto-Novo',
      logo_url: '/assets/logo-client.png',
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: company2Id,
      name: 'Bolloré Transport & Logistics',
      legal_name: 'Bolloré Africa Logistics Bénin SA',
      registration_number: 'RB/COT/18 B 87654',
      tax_number: 'IFU 0199834729103',
      email: 'contact.benin@bollore-logistics.com',
      phone: '+229 21 30 12 50',
      address: 'Zone Portuaire, Rue du Port',
      city: 'Cotonou',
      country: 'Bénin',
      currency: 'FCFA',
      timezone: 'Africa/Porto-Novo',
      logo_url: '/assets/logo-bollore.png',
      is_active: true,
      created_at: now,
      updated_at: now,
    },
  ];

  // 4. SITES
  const site1Id = 'site_cotonou_siege';
  const site2Id = 'site_port_cotonou';
  const site3Id = 'site_abomey_calavi';
  const site4Id = 'site_bollore_port';

  const sites = [
    {
      id: site1Id,
      company_id: company1Id,
      name: 'Siège - Cotonou',
      code: 'COT-HQ',
      city: 'Cotonou',
      address: 'Boulevard de la Marina',
      is_headquarters: true,
      created_at: now,
    },
    {
      id: site2Id,
      company_id: company1Id,
      name: 'Agence Port de Cotonou',
      code: 'COT-PORT',
      city: 'Cotonou',
      address: 'Quai Nord, Port de Cotonou',
      is_headquarters: false,
      created_at: now,
    },
    {
      id: site3Id,
      company_id: company1Id,
      name: 'Base Opérationnelle Calavi',
      code: 'CAL-BASE',
      city: 'Abomey-Calavi',
      address: 'Carrefour Tankpè',
      is_headquarters: false,
      created_at: now,
    },
    {
      id: site4Id,
      company_id: company2Id,
      name: 'Plateforme Terminal Bolloré',
      code: 'BOL-TERM',
      city: 'Cotonou',
      address: 'Terminal à conteneurs',
      is_headquarters: true,
      created_at: now,
    },
  ];

  // 5. DEPARTMENTS & COST CENTERS
  const departments = [
    { id: 'dept_dir_gen', company_id: company1Id, name: 'Direction Générale', code: 'DG' },
    { id: 'dept_logistique', company_id: company1Id, name: 'Logistique & Transport', code: 'LOG' },
    { id: 'dept_commercial', company_id: company1Id, name: 'Commercial & Ventes', code: 'COM' },
    { id: 'dept_technique', company_id: company1Id, name: 'Service Technique', code: 'TECH' },
  ];

  const costCenters = [
    { id: 'cc_dg', company_id: company1Id, name: 'Direction Générale', code: 'CC-001', budget_allocated: 15000000 },
    { id: 'cc_operations', company_id: company1Id, name: 'Exploitation & Flotte', code: 'CC-002', budget_allocated: 45000000 },
    { id: 'cc_commercial', company_id: company1Id, name: 'Équipe Commerciale', code: 'CC-003', budget_allocated: 20000000 },
  ];

  // 6. USERS
  const users = [
    // Global Super Admin (JMF Mobility Services)
    {
      id: 'usr_super_admin',
      company_id: null,
      first_name: 'Super',
      last_name: 'Administrateur JMF',
      email: 'admin@jmf-mobility.com',
      password_hash: hashPassword('admin123'),
      phone: '+229 01 97 83 21 21',
      role_id: 'SUPER_ADMIN_JMF' as const,
      site_id: undefined,
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    // Company Admin: Jean KOUASSI (Matches approved dashboard mockup)
    {
      id: 'usr_jean_kouassi',
      company_id: company1Id,
      first_name: 'Jean',
      last_name: 'KOUASSI',
      email: 'jean.kouassi@societe-cliente.com',
      password_hash: hashPassword('jmf2026'),
      phone: '+229 97 00 11 22',
      role_id: 'COMPANY_ADMIN' as const,
      site_id: site1Id,
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    // Fleet Manager: Koffi AMAN
    {
      id: 'usr_koffi_aman',
      company_id: company1Id,
      first_name: 'Koffi',
      last_name: 'AMAN',
      email: 'koffi.aman@societe-cliente.com',
      password_hash: hashPassword('jmf2026'),
      phone: '+229 95 33 44 55',
      role_id: 'FLEET_MANAGER' as const,
      site_id: site1Id,
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=256',
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    // Driver: Pierre DOSSOU
    {
      id: 'usr_pierre_dossou',
      company_id: company1Id,
      first_name: 'Pierre',
      last_name: 'DOSSOU',
      email: 'pierre.dossou@societe-cliente.com',
      password_hash: hashPassword('jmf2026'),
      phone: '+229 96 77 88 99',
      role_id: 'DRIVER' as const,
      site_id: site2Id,
      avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=256',
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    // Tenant 2 Admin: Marc ALLAGBE (Bolloré)
    {
      id: 'usr_bollore_admin',
      company_id: company2Id,
      first_name: 'Marc',
      last_name: 'ALLAGBE',
      email: 'marc.allagbe@bollore-logistics.com',
      password_hash: hashPassword('bollore2026'),
      phone: '+229 21 30 12 55',
      role_id: 'COMPANY_ADMIN' as const,
      site_id: site4Id,
      avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=256',
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    // Client User: Martin ADJOVI (Client / Donneur d'ordre)
    {
      id: 'usr_client_martin',
      company_id: company1Id,
      first_name: 'Martin',
      last_name: 'ADJOVI',
      email: 'martin.adjovi@afrique-transit.com',
      password_hash: hashPassword('client2026'),
      phone: '+229 97 12 34 56',
      role_id: 'CLIENT' as const,
      site_id: site1Id,
      avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=256',
      is_active: true,
      created_at: now,
      updated_at: now,
    },
  ];

  // 7. DRIVERS
  const driver1Id = 'drv_koffi_aman';
  const driver2Id = 'drv_pierre_dossou';
  const driver3Id = 'drv_bollore_driver';

  const drivers = [
    {
      id: driver1Id,
      company_id: company1Id,
      user_id: 'usr_koffi_aman',
      first_name: 'Koffi',
      last_name: 'AMAN',
      matricule: 'EMP-028',
      phone: '+229 95 33 44 55',
      email: 'koffi.aman@societe-cliente.com',
      license_number: 'BJ-PERMIS-2018-8849',
      license_category: 'B, C',
      license_issued_at: '2018-04-12',
      license_expires_at: '2028-04-12',
      status: 'active' as const,
      created_at: now,
    },
    {
      id: driver2Id,
      company_id: company1Id,
      user_id: 'usr_pierre_dossou',
      first_name: 'Pierre',
      last_name: 'DOSSOU',
      matricule: 'EMP-042',
      phone: '+229 96 77 88 99',
      email: 'pierre.dossou@societe-cliente.com',
      license_number: 'BJ-PERMIS-2019-3321',
      license_category: 'B',
      license_issued_at: '2019-06-20',
      license_expires_at: '2029-06-20',
      status: 'active' as const,
      created_at: now,
    },
    {
      id: driver3Id,
      company_id: company2Id,
      user_id: undefined,
      first_name: 'Alain',
      last_name: 'MENSAH',
      matricule: 'BOL-091',
      phone: '+229 97 12 34 56',
      email: 'alain.mensah@bollore-logistics.com',
      license_number: 'BJ-PERMIS-2017-9912',
      license_category: 'C, EC',
      license_issued_at: '2017-02-10',
      license_expires_at: '2027-02-10',
      status: 'active' as const,
      created_at: now,
    },
  ];

  // 8. VEHICLES (Real data reproducing mockups)
  const vehicle1Id = 'veh_peugeot_3008';
  const vehicle2Id = 'veh_renault_master';
  const vehicle3Id = 'veh_mercedes_actros';
  const vehicle4Id = 'veh_toyota_hilux';
  const vehicle5Id = 'veh_iveco_daily';
  const vehicle6Id = 'veh_bollore_truck';

  const vehicles = [
    // 1. Peugeot 3008 (Featured in vehicle detail mockup)
    {
      id: vehicle1Id,
      company_id: company1Id,
      site_id: site1Id,
      cost_center_id: 'cc_dg',
      current_driver_id: driver1Id,
      registration_number: 'BJ-1234-CD',
      vin: 'VF3MCYHZMNSI23456',
      brand: 'Peugeot',
      model: '3008',
      version: '1.5 BlueHDi 130 Allure Business',
      vehicle_type: 'VP' as const,
      category: 'SUV',
      color: 'Gris Platinium',
      year: 2022,
      first_registration_date: '2022-03-12',
      country: 'Bénin',
      energy_type: 'Diesel' as const,
      current_mileage: 56780,
      fuel_level_percent: 65,
      status: 'active' as const,
      acquisition_mode: 'LLD' as const,
      purchase_value: 28450000,
      monthly_lease: 450000,
      supplier: 'Bolloré Fleet Services',
      main_photo: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800',
      notes: 'Véhicule de fonction affecté à la Direction Générale. Excellent état général.',
      created_at: now,
      updated_at: now,
    },
    // 2. Renault Master
    {
      id: vehicle2Id,
      company_id: company1Id,
      site_id: site2Id,
      cost_center_id: 'cc_operations',
      current_driver_id: driver2Id,
      registration_number: 'BJ-5678-EF',
      vin: 'VF1MA00045678912',
      brand: 'Renault',
      model: 'Master',
      version: 'dCi 150 Grand Confort',
      vehicle_type: 'VUL' as const,
      category: 'Fourgon',
      color: 'Blanc Glacier',
      year: 2023,
      first_registration_date: '2023-01-15',
      country: 'Bénin',
      energy_type: 'Diesel' as const,
      current_mileage: 34200,
      fuel_level_percent: 80,
      status: 'active' as const,
      acquisition_mode: 'Achat comptant' as const,
      purchase_value: 22000000,
      monthly_lease: 0,
      supplier: 'CFAO Motors Bénin',
      main_photo: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=800',
      notes: 'Affecté aux navettes logistiques quotidiennes Cotonou - Calavi.',
      created_at: now,
      updated_at: now,
    },
    // 3. Mercedes Actros (En maintenance)
    {
      id: vehicle3Id,
      company_id: company1Id,
      site_id: site2Id,
      cost_center_id: 'cc_operations',
      current_driver_id: undefined,
      registration_number: 'BJ-9012-GH',
      vin: 'WDB9634031L893214',
      brand: 'Mercedes-Benz',
      model: 'Actros',
      version: '1845 LS StreamSpace',
      vehicle_type: 'Poids lourd' as const,
      category: 'Tracteur routier',
      color: 'Bleu JMF',
      year: 2021,
      first_registration_date: '2021-08-04',
      country: 'Bénin',
      energy_type: 'Diesel' as const,
      current_mileage: 184500,
      fuel_level_percent: 40,
      status: 'maintenance' as const,
      acquisition_mode: 'Crédit-bail' as const,
      purchase_value: 65000000,
      monthly_lease: 1100000,
      supplier: 'CFAO Motors',
      main_photo: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&q=80&w=800',
      notes: 'En révision complète au garage partenaire (freins & suspension).',
      created_at: now,
      updated_at: now,
    },
    // 4. Toyota Hilux
    {
      id: vehicle4Id,
      company_id: company1Id,
      site_id: site3Id,
      cost_center_id: 'cc_commercial',
      current_driver_id: undefined,
      registration_number: 'BJ-3456-IJ',
      vin: 'MROFR22G90123984',
      brand: 'Toyota',
      model: 'Hilux',
      version: 'Double Cabine 2.4 D-4D 4x4',
      vehicle_type: 'VUL' as const,
      category: 'Pick-up',
      color: 'Gris Métal',
      year: 2022,
      first_registration_date: '2022-09-10',
      country: 'Bénin',
      energy_type: 'Diesel' as const,
      current_mileage: 48900,
      fuel_level_percent: 90,
      status: 'active' as const,
      acquisition_mode: 'Achat comptant' as const,
      purchase_value: 26000000,
      monthly_lease: 0,
      supplier: 'CFAO Motors',
      main_photo: 'https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&q=80&w=800',
      notes: 'Missions régulières en province et corridors.',
      created_at: now,
      updated_at: now,
    },
    // 5. Iveco Daily (Immobilisé en panne)
    {
      id: vehicle5Id,
      company_id: company1Id,
      site_id: site3Id,
      cost_center_id: 'cc_operations',
      current_driver_id: undefined,
      registration_number: 'BJ-7890-KL',
      vin: 'ZCFC35890054321',
      brand: 'Iveco',
      model: 'Daily',
      version: '35S16 Fourgon',
      vehicle_type: 'VUL' as const,
      category: 'Fourgonnette',
      color: 'Blanc',
      year: 2020,
      first_registration_date: '2020-05-18',
      country: 'Bénin',
      energy_type: 'Diesel' as const,
      current_mileage: 98120,
      fuel_level_percent: 20,
      status: 'immobilized' as const,
      acquisition_mode: 'Achat comptant' as const,
      purchase_value: 18500000,
      monthly_lease: 0,
      supplier: 'Automobile Bénin',
      main_photo: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=800',
      notes: 'Panne moteur déclarée sur autoroute (injecteur défaillant). En attente remorquage.',
      created_at: now,
      updated_at: now,
    },
    // 6. Bolloré Logistics Truck (Company 2 for multi-tenant isolation test)
    {
      id: vehicle6Id,
      company_id: company2Id,
      site_id: site4Id,
      cost_center_id: undefined,
      current_driver_id: driver3Id,
      registration_number: 'BJ-9999-ZZ',
      vin: 'VNE9876543210123',
      brand: 'Scania',
      model: 'R450',
      version: 'Highline Streamline',
      vehicle_type: 'Poids lourd' as const,
      category: 'Tracteur Portuaire',
      color: 'Bleu Bolloré',
      year: 2023,
      first_registration_date: '2023-04-01',
      country: 'Bénin',
      energy_type: 'Diesel' as const,
      current_mileage: 41200,
      fuel_level_percent: 75,
      status: 'active' as const,
      acquisition_mode: 'LLD' as const,
      purchase_value: 72000000,
      monthly_lease: 1350000,
      supplier: 'Scania West Africa',
      main_photo: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&q=80&w=800',
      notes: 'Flotte exclusive Bolloré Logistics Portuaire.',
      created_at: now,
      updated_at: now,
    },
    // 7. Suzuki Vitara Pool (Disponible)
    {
      id: 'veh_suzuki_vitara',
      company_id: company1Id,
      site_id: site1Id,
      cost_center_id: 'cc_dg',
      current_driver_id: undefined,
      registration_number: 'BJ-4567-MN',
      vin: 'TSMEYD21S00987654',
      brand: 'Suzuki',
      model: 'Vitara',
      version: '1.4 Boosterjet Hybrid AllGrip',
      vehicle_type: 'VP' as const,
      category: 'SUV Pool & Missions',
      color: 'Blanc Nacré',
      year: 2024,
      first_registration_date: '2024-02-10',
      country: 'Bénin',
      energy_type: 'Hybride' as const,
      current_mileage: 12400,
      fuel_level_percent: 95,
      status: 'available' as const,
      acquisition_mode: 'Achat comptant' as const,
      purchase_value: 19800000,
      monthly_lease: 0,
      supplier: 'CFAO Motors Bénin',
      main_photo: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800',
      notes: 'Véhicule en pool de partage, disponible pour réservations et ordres de mission.',
      created_at: now,
      updated_at: now,
    },
    // 8. Toyota Corolla Pool (Disponible)
    {
      id: 'veh_toyota_corolla',
      company_id: company1Id,
      site_id: site2Id,
      cost_center_id: 'cc_operations',
      current_driver_id: undefined,
      registration_number: 'BJ-6789-OP',
      vin: 'JTNKW3HE90J123890',
      brand: 'Toyota',
      model: 'Corolla',
      version: '1.8 Hybrid Dynamic Business',
      vehicle_type: 'VP' as const,
      category: 'Berline Pool Déplacements',
      color: 'Gris Argent',
      year: 2023,
      first_registration_date: '2023-05-14',
      country: 'Bénin',
      energy_type: 'Hybride' as const,
      current_mileage: 28900,
      fuel_level_percent: 75,
      status: 'available' as const,
      acquisition_mode: 'LLD' as const,
      purchase_value: 21500000,
      monthly_lease: 520000,
      supplier: 'CFAO Motors Bénin',
      main_photo: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&q=80&w=800',
      notes: 'Véhicule de pool stationné au Port de Cotonou, prêt pour mission.',
      created_at: now,
      updated_at: now,
    },
    // 9. Peugeot 406 (Réformé)
    {
      id: 'veh_peugeot_406_reforme',
      company_id: company1Id,
      site_id: site1Id,
      cost_center_id: 'cc_operations',
      current_driver_id: undefined,
      registration_number: 'BJ-0123-AA',
      vin: 'VF38BRHZF81234901',
      brand: 'Peugeot',
      model: '406',
      version: '2.0 HDi 110 SR Confort',
      vehicle_type: 'VP' as const,
      category: 'Véhicule Réformé',
      color: 'Bleu de Chine',
      year: 2012,
      first_registration_date: '2012-04-20',
      country: 'Bénin',
      energy_type: 'Diesel' as const,
      current_mileage: 382400,
      fuel_level_percent: 10,
      status: 'retired' as const,
      acquisition_mode: 'Achat comptant' as const,
      purchase_value: 12500000,
      monthly_lease: 0,
      supplier: 'Ancien parc JMF',
      main_photo: 'https://images.unsplash.com/photo-1541443131876-44b03de101c5?auto=format&fit=crop&q=80&w=800',
      notes: 'Véhicule amorti à 100%, réformé le 15/01/2026. En attente de vente aux enchères.',
      created_at: now,
      updated_at: now,
    },
  ];

  // 9. VEHICLE ASSIGNMENTS
  const vehicle_assignments = [
    {
      id: 'asg_peugeot_koffi',
      vehicle_id: vehicle1Id,
      driver_id: driver1Id,
      start_at: '2022-03-15T08:00:00Z',
      end_at: undefined,
      mileage_start: 120,
      condition_start: 'Véhicule neuf reçu en parfait état.',
      created_at: now,
    },
    {
      id: 'asg_master_pierre',
      vehicle_id: vehicle2Id,
      driver_id: driver2Id,
      start_at: '2023-02-01T08:00:00Z',
      end_at: undefined,
      mileage_start: 250,
      condition_start: 'Fourgon livré conforme avec pack outillage.',
      created_at: now,
    },
  ];

  // 10. DOCUMENTS
  const documents = [
    {
      id: 'doc_assurance_peugeot',
      company_id: company1Id,
      vehicle_id: vehicle1Id,
      type: 'insurance' as const,
      reference: 'POL-NSIA-2026-9938',
      issuer: 'NSIA Assurances Bénin',
      issued_at: '2026-02-15',
      expires_at: '2027-02-14',
      file_url: '/documents/assurance-bj-1234-cd.pdf',
      status: 'valid' as const,
      created_at: now,
    },
    {
      id: 'doc_visite_peugeot',
      company_id: company1Id,
      vehicle_id: vehicle1Id,
      type: 'technical_inspection' as const,
      reference: 'VT-ANaTT-2026-1120',
      issuer: 'ANaTT Cotonou',
      issued_at: '2025-05-20',
      expires_at: '2026-05-20',
      file_url: '/documents/vt-bj-1234-cd.pdf',
      status: 'expiring_soon' as const, // Échéance sous 30 jours
      created_at: now,
    },
    {
      id: 'doc_cg_peugeot',
      company_id: company1Id,
      vehicle_id: vehicle1Id,
      type: 'registration_card' as const,
      reference: 'CG-BEN-892348',
      issuer: 'Ministère des Transports Bénin',
      issued_at: '2022-03-12',
      expires_at: undefined,
      file_url: '/documents/carte-grise-bj-1234-cd.pdf',
      status: 'valid' as const,
      created_at: now,
    },
    {
      id: 'doc_assurance_daily_expired',
      company_id: company1Id,
      vehicle_id: vehicle5Id,
      type: 'insurance' as const,
      reference: 'POL-SUNU-2025-0012',
      issuer: 'SUNU Assurances',
      issued_at: '2025-01-10',
      expires_at: '2026-01-09',
      file_url: '/documents/assurance-iveco.pdf',
      status: 'expired' as const, // Expiré !
      created_at: now,
    },
  ];

  // 11. WORK ORDERS
  const work_orders = [
    {
      id: 'wo_vidange_peugeot',
      company_id: company1Id,
      vehicle_id: vehicle1Id,
      title: 'Vidange moteur + Remplacement filtres',
      intervention_type: 'Vidange + Filtres',
      scheduled_date: '2026-05-15',
      completed_date: undefined,
      mileage_at_intervention: 58000,
      workshop_name: 'Garage CFAO Cotonou',
      cost: 145000,
      status: 'scheduled' as const,
      notes: 'Vidange synthèse 5W30 + filtre huile, air et habitacle.',
      created_at: now,
    },
    {
      id: 'wo_revision_master',
      company_id: company1Id,
      vehicle_id: vehicle2Id,
      title: 'Révision générale 30 000 km',
      intervention_type: 'Révision générale',
      scheduled_date: '2026-05-18',
      completed_date: undefined,
      mileage_at_intervention: 35000,
      workshop_name: 'Atelier JMF Services',
      cost: 210000,
      status: 'scheduled' as const,
      notes: 'Contrôle plaquettes, vidange boîte et purge circuit.',
      created_at: now,
    },
    {
      id: 'wo_freins_actros',
      company_id: company1Id,
      vehicle_id: vehicle3Id,
      title: 'Contrôle et réfection système freinage pneumatique',
      intervention_type: 'Contrôle freins',
      scheduled_date: '2026-05-20',
      completed_date: undefined,
      mileage_at_intervention: 185000,
      workshop_name: 'Atelier Poids Lourds Cotonou',
      cost: 850000,
      status: 'in_progress' as const,
      notes: 'Changement garnitures essieu arrière.',
      created_at: now,
    },
  ];

  // 12. FUEL ENTRIES
  const fuel_entries = [
    {
      id: 'fuel_01',
      company_id: company1Id,
      vehicle_id: vehicle1Id,
      driver_id: driver1Id,
      date: '2026-05-28T14:32:00Z',
      station_name: 'TotalEnergies Marina Cotonou',
      fuel_type: 'Diesel',
      liters: 42.5,
      price_per_liter: 1365,
      amount: 58000,
      mileage: 56780,
      receipt_url: '/receipts/total-rec-58000.jpg',
      created_at: now,
    },
    {
      id: 'fuel_02',
      company_id: company1Id,
      vehicle_id: vehicle1Id,
      driver_id: driver1Id,
      date: '2026-05-12T09:15:00Z',
      station_name: 'Puma Energy Calavi',
      fuel_type: 'Diesel',
      liters: 38.0,
      price_per_liter: 1365,
      amount: 51870,
      mileage: 56120,
      receipt_url: '/receipts/puma-rec-51870.jpg',
      created_at: now,
    },
    {
      id: 'fuel_03',
      company_id: company1Id,
      vehicle_id: vehicle2Id,
      driver_id: driver2Id,
      date: '2026-05-25T16:00:00Z',
      station_name: 'TotalEnergies Port Cotonou',
      fuel_type: 'Diesel',
      liters: 65.0,
      price_per_liter: 1365,
      amount: 88725,
      mileage: 34150,
      receipt_url: '/receipts/total-rec-88725.jpg',
      created_at: now,
    },
  ];

  // 13. ALERTS
  const alerts = [
    {
      id: 'alert_01',
      company_id: company1Id,
      vehicle_id: vehicle5Id,
      type: 'DANGER' as const,
      category: 'insurance' as const,
      title: 'Assurance expirée',
      message: 'L’assurance du véhicule Iveco Daily BJ-7890-KL est expirée depuis le 09/01/2026.',
      is_read: false,
      created_at: now,
    },
    {
      id: 'alert_02',
      company_id: company1Id,
      vehicle_id: vehicle1Id,
      type: 'WARNING' as const,
      category: 'inspection' as const,
      title: 'Visite technique à échéance',
      message: 'La visite technique du véhicule Peugeot 3008 BJ-1234-CD expire le 20/05/2026.',
      is_read: false,
      created_at: now,
    },
    {
      id: 'alert_03',
      company_id: company1Id,
      vehicle_id: vehicle3Id,
      type: 'WARNING' as const,
      category: 'maintenance' as const,
      title: 'Maintenance programmée',
      message: 'Le tracteur Actros BJ-9012-GH est en cours d’intervention (freinage).',
      is_read: false,
      created_at: now,
    },
    {
      id: 'alert_04',
      company_id: company1Id,
      vehicle_id: vehicle5Id,
      type: 'DANGER' as const,
      category: 'breakdown' as const,
      title: 'Panne moteur déclarée',
      message: 'Véhicule BJ-7890-KL immobilisé sur autoroute Cotonou-Ouidah.',
      is_read: false,
      created_at: now,
    },
  ];

  // 14. ACTIVITY & AUDIT LOGS (Compliance ISO 27001 & DGI e-MECeF)
  const activity_logs: any[] = [
    {
      id: 'act_01',
      company_id: null,
      company_name: 'JMF Mobility Services',
      user_id: 'usr_super_admin',
      user_name: 'Super Administrateur JMF',
      user_role: 'SUPER_ADMIN_JMF',
      entity_type: 'user',
      entity_id: 'usr_jean_kouassi',
      action: 'Modification de rôle administrateur',
      description: 'Élévation de privilèges : Rôle attribué à Jean KOUASSI passé de GESTIONNAIRE_FLOTTE à COMPANY_ADMIN.',
      severity: 'critical',
      compliance_tag: 'ROLE_CHANGE',
      ip_address: '197.234.221.14 (Direction Cotonou)',
      changes: [
        { field: 'role_id', old_value: 'FLEET_MANAGER', new_value: 'COMPANY_ADMIN' }
      ],
      hash_checksum: 'a8f5e71c901e4a3b8d6291a50bdf738e4c9f11a8b9e6f3d1a8e9f2b3c4d5e6f7',
      created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    },
    {
      id: 'act_02',
      company_id: company1Id,
      company_name: 'Société Cliente SARL Bénin',
      user_id: 'usr_super_admin',
      user_name: 'Super Administrateur JMF',
      user_role: 'SUPER_ADMIN_JMF',
      entity_type: 'invoice',
      entity_id: 'inv_2026_09',
      action: 'Ajustement et rapprochement comptable',
      description: 'Facture FAC-JMF-2026-09-089 (MECeF: DGI-BJ-20260921-99812-MECeF) : statut passé de Émise à Validée / Règlement Enregistré.',
      severity: 'warning',
      compliance_tag: 'INVOICE_MODIFICATION',
      ip_address: '197.234.221.14 (Direction Cotonou)',
      changes: [
        { field: 'status', old_value: 'SENT', new_value: 'PAID' },
        { field: 'payment_method', old_value: null, new_value: 'Virement bancaire BOA Bénin' }
      ],
      hash_checksum: 'c4e7f91a2b3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f',
      created_at: new Date(Date.now() - 95 * 60 * 1000).toISOString(),
    },
    {
      id: 'act_03',
      company_id: company1Id,
      company_name: 'Société Cliente SARL Bénin',
      user_id: 'usr_jean_kouassi',
      user_name: 'Jean KOUASSI',
      user_role: 'COMPANY_ADMIN',
      entity_type: 'user',
      entity_id: 'usr_koffi_aman',
      action: 'Attribution rôle Conducteur Principal',
      description: 'Changement de statut conducteur et certification pool pour Koffi AMAN.',
      severity: 'warning',
      compliance_tag: 'ROLE_CHANGE',
      ip_address: '41.85.160.78 (Akpakpa)',
      changes: [
        { field: 'role_id', old_value: 'USER', new_value: 'DRIVER' }
      ],
      hash_checksum: 'd1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2',
      created_at: new Date(Date.now() - 4 * 3600000).toISOString(),
    },
    {
      id: 'act_04',
      company_id: company1Id,
      company_name: 'Société Cliente SARL Bénin',
      user_id: 'usr_super_admin',
      user_name: 'Super Administrateur JMF',
      user_role: 'SUPER_ADMIN_JMF',
      entity_type: 'invoice',
      entity_id: 'inv_2026_09_02',
      action: 'Modification d’échéance facture',
      description: 'Facture FAC-JMF-2026-09-090 : échéance de paiement reportée au 15/10/2026 suite accord commercial.',
      severity: 'info',
      compliance_tag: 'INVOICE_MODIFICATION',
      ip_address: '197.234.221.14 (Direction Cotonou)',
      changes: [
        { field: 'due_date', old_value: '2026-09-30', new_value: '2026-10-15' }
      ],
      hash_checksum: 'b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4',
      created_at: new Date(Date.now() - 8 * 3600000).toISOString(),
    },
    {
      id: 'act_05',
      company_id: null,
      company_name: 'JMF Mobility Services',
      user_id: 'usr_super_admin',
      user_name: 'Super Administrateur JMF',
      user_role: 'SUPER_ADMIN_JMF',
      entity_type: 'security',
      entity_id: 'usr_pierre_dossou',
      action: 'Réinitialisation de mot de passe administrateur',
      description: 'Demande de renouvellement de mot de passe générée et lien à usage unique envoyé par canal sécurisé.',
      severity: 'warning',
      compliance_tag: 'PASSWORD_RESET',
      ip_address: '197.234.221.14 (Direction Cotonou)',
      hash_checksum: 'e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6',
      created_at: new Date(Date.now() - 14 * 3600000).toISOString(),
    },
    {
      id: 'act_06',
      company_id: company1Id,
      company_name: 'Société Cliente SARL Bénin',
      user_id: 'usr_koffi_aman',
      user_name: 'Koffi AMAN',
      user_role: 'DRIVER',
      entity_type: 'fuel_entry',
      entity_id: 'fuel_01',
      action: 'Plein de carburant enregistré',
      description: 'Plein de 42,5 L (58 000 FCFA) saisi pour le véhicule BJ-1234-CD.',
      severity: 'info',
      compliance_tag: 'FLEET_OPERATION',
      ip_address: '41.85.160.78',
      created_at: new Date(Date.now() - 18 * 3600000).toISOString(),
    },
  ];

  // 17. INVOICES
  const invoices: any[] = [
    {
      id: 'inv_2026_09',
      invoice_number: 'FAC-JMF-2026-09-089',
      emef_code: 'DGI-BJ-20260921-99812-MECeF',
      company_id: company1Id,
      user_id: 'usr_jean_kouassi',
      period: 'Septembre 2026',
      issue_date: '2026-09-01',
      due_date: '2026-09-30',
      service_type: 'fleet_management',
      description: 'Forfait mensuel Gestion de flotte & Télématique IoT (125 véhicules)',
      quantity: 125,
      unit_price: 28813.56,
      tax_rate: 18,
      discount: 0,
      amount_ht: 3601695,
      amount_tva: 648305,
      amount_ttc: 4250000,
      currency: 'FCFA',
      status: 'PENDING',
      payment_method: 'Virement bancaire / MoMo Business en attente',
      items_breakdown: [
        { label: 'Abonnement Plateforme SaaS JMF & Passerelle IoT (125 véh.)', qty: 125, unit_price: 15000, total: 1875000 },
        { label: 'Supervision & Maintenance préventive déléguée (Atelier)', qty: 1, unit_price: 1200000, total: 1200000 },
        { label: 'Audit conformité & gestion des visites CNSR (Pack mensuel)', qty: 1, unit_price: 526695, total: 526695 },
      ],
      created_at: '2026-09-01T08:00:00.000Z',
      updated_at: '2026-09-01T08:00:00.000Z',
    },
    {
      id: 'inv_2026_08',
      invoice_number: 'FAC-JMF-2026-08-084',
      emef_code: 'DGI-BJ-20260820-88124-MECeF',
      company_id: company1Id,
      user_id: 'usr_jean_kouassi',
      period: 'Août 2026',
      issue_date: '2026-08-01',
      due_date: '2026-08-31',
      service_type: 'maintenance',
      description: 'Gestion de flotte, renouvellement assurances NSIA et révisions d’atelier',
      quantity: 1,
      unit_price: 3372881,
      tax_rate: 18,
      discount: 0,
      amount_ht: 3372881,
      amount_tva: 607119,
      amount_ttc: 3980000,
      currency: 'FCFA',
      status: 'PAID',
      payment_method: 'Virement BOA Bénin #992481',
      payment_date: '2026-08-28',
      transaction_ref: 'TRX-BOA-20260828-0912',
      items_breakdown: [
        { label: 'Abonnement Plateforme SaaS JMF & Passerelle IoT (125 véh.)', qty: 125, unit_price: 15000, total: 1875000 },
        { label: 'Forfait Révisions d’atelier et filtres parc Cotonou', qty: 1, unit_price: 1100000, total: 1100000 },
        { label: 'Courtage & renouvellement polices d’assurance NSIA', qty: 1, unit_price: 397881, total: 397881 },
      ],
      created_at: '2026-08-01T08:00:00.000Z',
      updated_at: '2026-08-28T14:30:00.000Z',
    },
    {
      id: 'inv_2026_convoy_01',
      invoice_number: 'FAC-JMF-2026-09-090',
      emef_code: 'DGI-BJ-20260921-99813-MECeF',
      company_id: company1Id,
      user_id: 'usr_client_martin',
      period: 'Septembre 2026',
      issue_date: '2026-09-18',
      due_date: '2026-09-30',
      service_type: 'convoy',
      reference_mission: 'JMF-CONV-2026-000001',
      description: 'Convoyage professionnel routier sécurisé : Toyota Hilux (Cotonou -> Parakou)',
      quantity: 1,
      unit_price: 150000,
      tax_rate: 18,
      discount: 0,
      amount_ht: 150000,
      amount_tva: 27000,
      amount_ttc: 177000,
      currency: 'FCFA',
      status: 'PENDING',
      payment_method: 'Mobile Money MTN Bénin / Virement',
      items_breakdown: [
        { label: 'Convoyage routier par conducteur dédié (420 km)', qty: 1, unit_price: 120000, total: 120000 },
        { label: 'Frais d’assurance transit & péages interurbains', qty: 1, unit_price: 30000, total: 30000 },
      ],
      created_at: '2026-09-18T10:00:00.000Z',
      updated_at: '2026-09-18T10:00:00.000Z',
    },
  ];

  // 18. CONVOY REQUESTS
  const convoy_requests: any[] = [
    {
      id: 'conv_001',
      reference: 'JMF-CONV-2026-000001',
      company_id: company1Id,
      user_id: 'usr_client_martin',
      status: 'IN_PROGRESS',
      vehicle_brand: 'Toyota',
      vehicle_model: 'Hilux Double Cabine 4x4',
      vehicle_year: 2022,
      vehicle_plate: 'BJ-5544-CD',
      is_registered: true,
      vehicle_color: 'Gris Métallisé',
      vehicle_condition: 'good',
      condition_details: 'Véhicule en parfait état de fonctionnement, contrôle technique valide.',
      requires_flatbed: false,
      pickup_address: 'Boulevard de la Marina, Lot 45',
      pickup_city: 'Cotonou',
      pickup_country: 'Bénin',
      delivery_address: 'Direction Régionale Afrique Transit, Quartier Titirou',
      delivery_city: 'Parakou',
      delivery_country: 'Bénin',
      desired_date: '2026-09-24',
      desired_time: '07:30',
      convoy_type: 'company',
      convoy_mode: 'driver',
      access_instructions: 'Clés disponibles auprès de l’accueil sécurité.',
      client_name: 'Martin ADJOVI',
      client_company: 'Afrique Transit SA',
      client_email: 'martin.adjovi@afrique-transit.com',
      client_phone: '+229 97 12 34 56',
      client_country: 'Bénin',
      special_instructions: 'Livraison express avant 16h00 si possible.',
      privacy_accepted: true,
      internal_notes: 'Mission assignée au conducteur Koffi AMAN. Véhicule inspecté.',
      assigned_driver_id: 'drv_koffi_aman',
      quote_amount: 177000,
      invoice_id: 'inv_2026_convoy_01',
      timeline: [
        {
          id: 'tl_01',
          status: 'NEW',
          label: 'Demande créée',
          note: 'Formulaire reçu via portail public',
          author: 'Système JMF',
          created_at: '2026-09-17T14:15:00.000Z',
        },
        {
          id: 'tl_02',
          status: 'QUOTE_SENT',
          label: 'Devis envoyé',
          note: 'Devis de 177 000 FCFA TTC transmis au client',
          author: 'Super Admin JMF',
          created_at: '2026-09-18T09:30:00.000Z',
        },
        {
          id: 'tl_03',
          status: 'ACCEPTED',
          label: 'Devis accepté',
          note: 'Validation reçue par email',
          author: 'Martin ADJOVI',
          created_at: '2026-09-18T11:00:00.000Z',
        },
        {
          id: 'tl_04',
          status: 'IN_PROGRESS',
          label: 'Mission en cours',
          note: 'Conducteur en route vers le point de prise en charge',
          author: 'Koffi AMAN',
          created_at: '2026-09-21T08:00:00.000Z',
        },
      ],
      created_at: '2026-09-17T14:15:00.000Z',
      updated_at: '2026-09-21T08:00:00.000Z',
    },
    {
      id: 'conv_002',
      reference: 'JMF-CONV-2026-000002',
      company_id: null,
      user_id: null,
      status: 'NEW',
      vehicle_brand: 'Peugeot',
      vehicle_model: '3008 Allure',
      vehicle_year: 2021,
      vehicle_plate: 'BJ-8899-EF',
      is_registered: true,
      vehicle_color: 'Blanc Nacré',
      vehicle_condition: 'good',
      condition_details: 'Véhicule sortant de révision, documents complets.',
      requires_flatbed: false,
      pickup_address: 'Port Autonome de Cotonou, Quai Nord',
      pickup_city: 'Cotonou',
      pickup_country: 'Bénin',
      delivery_address: 'Zone Industrielle Glo-Djigbé (GDIZ), Dépôt B',
      delivery_city: 'Glo-Djigbé',
      delivery_country: 'Bénin',
      desired_date: '2026-09-25',
      desired_time: '09:00',
      convoy_type: 'warehouse_transfer',
      convoy_mode: 'to_be_determined',
      access_instructions: 'Badge portuaire exigé pour le convoyeur.',
      client_name: 'Bolloré Logistics Transit',
      client_company: 'Bolloré Transport & Logistics Bénin',
      client_email: 'transit@bollore-logistics.com',
      client_phone: '+229 21 30 12 00',
      client_country: 'Bénin',
      special_instructions: 'Vérification méticuleuse de la fiche d’état des lieux au départ.',
      privacy_accepted: true,
      internal_notes: 'Nouvelle demande reçue. Nécessite accréditation portuaire.',
      timeline: [
        {
          id: 'tl_02_1',
          status: 'NEW',
          label: 'Nouvelle demande reçue',
          note: 'En attente de chiffrage par l’équipe JMF',
          author: 'Système JMF',
          created_at: '2026-09-21T10:00:00.000Z',
        },
      ],
      created_at: '2026-09-21T10:00:00.000Z',
      updated_at: '2026-09-21T10:00:00.000Z',
    },
    {
      id: 'conv_003',
      reference: 'JMF-CONV-2026-000003',
      company_id: null,
      user_id: null,
      status: 'QUOTE_SENT',
      vehicle_brand: 'Mercedes-Benz',
      vehicle_model: 'Sprinter Fourgon 316 CDI',
      vehicle_year: 2019,
      vehicle_plate: 'TG-1234-AB',
      is_registered: true,
      vehicle_color: 'Bleu Nuit',
      vehicle_condition: 'breakdown',
      condition_details: 'Embrayage HS, nécessite impérativement un camion plateau porte-voiture.',
      requires_flatbed: true,
      pickup_address: 'Port de Lomé, Zone Franche',
      pickup_city: 'Lomé',
      pickup_country: 'Togo',
      delivery_address: 'Hub Atelier Central JMF, Akpakpa',
      delivery_city: 'Cotonou',
      delivery_country: 'Bénin',
      desired_date: '2026-09-28',
      desired_time: '08:00',
      convoy_type: 'agency_transfer',
      convoy_mode: 'flatbed',
      access_instructions: 'Véhicule sous douane, bordereau de transit transfrontalier fourni.',
      client_name: 'Koffi ADANHO',
      client_company: 'Société de Distribution Ouest-Africaine',
      client_email: 'logistique@sdo-afrique.com',
      client_phone: '+228 90 11 22 33',
      client_country: 'Togo',
      special_instructions: 'Prise en charge par camion plateau à 8h.',
      privacy_accepted: true,
      internal_notes: 'Devis de 320 000 FCFA envoyé pour plateau transfrontalier.',
      quote_amount: 320000,
      timeline: [
        {
          id: 'tl_03_1',
          status: 'NEW',
          label: 'Demande enregistrée',
          note: 'Véhicule non roulant nécessitant transport adapté',
          author: 'Système JMF',
          created_at: '2026-09-20T11:20:00.000Z',
        },
        {
          id: 'tl_03_2',
          status: 'QUOTE_SENT',
          label: 'Devis transmis',
          note: 'Devis transport plateau Togo -> Bénin : 320 000 FCFA TTC',
          author: 'Super Admin JMF',
          created_at: '2026-09-20T15:40:00.000Z',
        },
      ],
      created_at: '2026-09-20T11:20:00.000Z',
      updated_at: '2026-09-20T15:40:00.000Z',
    },
  ];

  // 19. EMAIL LOGS
  const email_logs: any[] = [
    {
      id: 'eml_01',
      to: 'martin.adjovi@afrique-transit.com',
      recipient_name: 'Martin ADJOVI',
      subject: 'Confirmation de réception de votre demande de convoyage — Réf : JMF-CONV-2026-000001',
      body: 'Bonjour Martin ADJOVI,\n\nNous avons bien reçu votre demande de convoyage pour le véhicule Toyota Hilux.\nVotre référence de dossier est : JMF-CONV-2026-000001.\nNotre équipe commerciale examine votre demande et vous contactera dans les plus brefs délais.\n\nCordialement,\nJMF Mobility Services',
      type: 'CONVOY_CONFIRMATION',
      status: 'sent',
      retry_count: 0,
      created_at: '2026-09-17T14:15:05.000Z',
      sent_at: '2026-09-17T14:15:06.000Z',
    },
    {
      id: 'eml_02',
      to: 'jmfmobility.services@gmail.com',
      recipient_name: 'Équipe Opérations JMF',
      subject: '[NOUVELLE DEMANDE DE CONVOYAGE] Réf : JMF-CONV-2026-000001 — Martin ADJOVI',
      body: 'Une nouvelle demande de convoyage a été soumise sur le portail public JMF.\nRéférence : JMF-CONV-2026-000001\nVéhicule : Toyota Hilux 2022\nPrise en charge : Cotonou -> Livraison : Parakou',
      type: 'JMF_INTERNAL_ALERT',
      status: 'sent',
      retry_count: 0,
      created_at: '2026-09-17T14:15:06.000Z',
      sent_at: '2026-09-17T14:15:07.000Z',
    },
  ];

  return {
    companies,
    sites,
    departments,
    cost_centers: costCenters,
    roles,
    permissions,
    role_permissions,
    users,
    personal_access_tokens: [],
    drivers,
    vehicles,
    vehicle_assignments,
    documents,
    work_orders,
    fuel_entries,
    alerts,
    activity_logs,
    convoy_requests,
    invoices,
    email_logs,
  };
}
